MyCVHenrikPrangel/Models/ErrorViewModel.cs
using System;

namespace MyCVHenrikPrangel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyCVHenrikPrangel/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.App.Interfaces;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace MyCVHenrikPrangel.Controllers
{
    public class ExperienceController : Controller
    {
        private readonly IAppUnitOfWork _uow;
        private readonly Person person;

        public ExperienceController(IAppUnitOfWork uow)
        {
            _uow = uow;
            person = _uow.People.All().First();

        }

        public IActionResult Education()
        {
            @ViewData["Page"] = "Education";
            @ViewData["FirstName"] = person.Firstname;
            @ViewData["LastName"] = person.Lastname;
            ViewData["Message"] = "Your application description page.";

            return View(_uow.Experiences.All().Where(x => x.ExperienceType == Domain.Enums.ExperienceType.Education && x.PersonId == person.PersonId).ToList());
        }

        public IActionResult WorkExperience()
        {
            @ViewData["Page"] = "Work Experience";
            @ViewData["FirstName"] = person.Firstname;
            @ViewData["LastName"] = person.Lastname;

            var exp = _uow.Experiences.All().Where(x => x.ExperienceType == Domain.Enums.ExperienceType.WorkExperience
            && x.PersonId == person.PersonId).ToList();
            if (exp.Count() < 1)
            {
                ViewData["Message"] = "At the moment, i have no professional work experience, besides the odd couple summer jobs, completely unrelated to IT";
            }
            return View(exp);
        }

    }
}

MyCVHenrikPrangel/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.App.Interfaces;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace MyCVHenrikPrangel.Controllers
{
    public class PersonController : Controller
    {
        private readonly IAppUnitOfWork _uow;
        private readonly Person person;

        public PersonController(IAppUnitOfWork uow)
        {
            _uow = uow;
#warning This is fine for this project, but definetly needs to be reworked if made into a real website
            //Currently, only one person shall be held in the Database, so this works for now
            person = _uow.People.All().First();

        }


        public IActionResult Index()
        {
            @ViewData["FirstName"] = person.Firstname;
            @ViewData["LastName"] = person.Lastname;
            @ViewData["Email"] = person.Email;
            @ViewData["PersDesc"] = person.PersonDescription;
            @ViewData["PhoneNr"] = person.Phonenumber;
            @ViewData["Address"] = person.Address;
            return View();
        }
    }
}

MyCVHenrikPrangel/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.App.Interfaces;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace MyCVHenrikPrangel.Controllers
{
    public class SkillsController : Controller
    {
        private readonly IAppUnitOfWork _uow;
        private readonly Person person;

        public SkillsController(IAppUnitOfWork uow)
        {
            _uow = uow;
            person = _uow.People.All().First();

        }
        public IActionResult Skills()
        {
            @ViewData["Page"] = "Skills and Abilites";
            @ViewData["FirstName"] = person.Firstname;
            @ViewData["LastName"] = person.Lastname;
            ViewData["Message"] = "Your contact page.";

            return View(_uow.Skills.All().Where(x => x.PersonId == person.PersonId).ToList());
        }
        public IActionResult Languages()
        {
            @ViewData["Page"] = "Languages";
            @ViewData["FirstName"] = person.Firstname;
            @ViewData["LastName"] = person.Lastname;
            return View(_uow.Languages.All().Where(x => x.PersonId == person.PersonId).ToList());
        }
    }
}

MyCVHenrikPrangel/Views/Experience/Education.cshtml
@model IEnumerable<Domain.Experience>

@{
    ViewData["Title"] = "Education";
}
<br />
<br />
<br />
<section class="resume-section">
    <section class="table">
        <table width="1000" height="200" class="subheading mb-5">
            <thead class="table-dark">
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateFrom.Year)
                            -                            
                            @Html.DisplayFor(modelItem => item.DateUntil.Year)
                        </td>
                        <td>
                            <span class="text-dark">
                                @Html.DisplayFor(modelItem => item.InstitutionName) ,
                            </span>
                            @Html.DisplayFor(modelItem => item.InstitutionLocation)                            
                        </td>
                        <td>
                            - @Html.DisplayFor(modelItem => item.Information)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </section>
</section>

MyCVHenrikPrangel/Views/Experience/WorkExperience.cshtml
@model IEnumerable<Domain.Experience>

@{
    ViewData["Title"] = "Work Experience";
}
<br />
<br />
<br />
<p>@ViewData["Message"]</p>
<section class="resume-section">
    <section class="table">
        <table width="1000" height="200" class="subheading mb-5">
            <thead class="table-dark">
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateFrom.Year)
                            -
                            @Html.DisplayFor(modelItem => item.DateUntil.Year)
                        </td>
                        <td>
                            <span class="text-dark">
                                @Html.DisplayFor(modelItem => item.InstitutionName) ,
                            </span>
                            @Html.DisplayFor(modelItem => item.InstitutionLocation)                            
                        </td>
                        <td>
                            - @Html.DisplayFor(modelItem => item.Information)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </section>
</section>

MyCVHenrikPrangel/Views/Person/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<section class="resume-section p-3 p-lg-5 d-flex d-column">
    <div>
        <div class="subheading mb-5">
            <table width="550">
                <tr>
                    <th>First name : </th>
                    <th class="text-dark"> @ViewData["FirstName"]</th>

                </tr>
                <tr>
                    <th>Last name : </th>
                    <th class="text-dark">@ViewData["LastName"]</th>
                </tr>
                <tr>
                    <th>Address : </th>
                    <th class="text-dark"> @ViewData["Address"]</th>
                </tr>
                <tr>
                    <th>Phone nr. : </th>
                    <th class="text-dark"> @ViewData["PhoneNr"]</th>
                </tr>
                <tr>
                    <th>E-Mail : </th>
                    <th class="text-dark"><a href="mailto:name@email.com">@ViewData["Email"]</a></th>
                </tr>
            </table>
        </div>
        @* Forgot to add the bitbucket link to the DB *@
        <p class="mb-5">Bitbucket: <a href="https://bitbucket.org/HenrikPrangel"> My other projects</a></p>
        <p class="mb-5"> @ViewData["PersDesc"]</p>
    </div>
    </section>

MyCVHenrikPrangel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Henrik Prangel CV</title>

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="vendor/devicons/css/devicons.min.css" rel="stylesheet">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

    <environment include="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/resume.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/resume.min.css" asp-append-version="true" />
    </environment>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Person" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Experience" asp-action="Education">Education</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Experience" asp-action="WorkExperience">Work Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Skills" asp-action="Skills">Skills and Abilities</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Skills" asp-action="Languages">Languages</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        <section class="resume-section p-3 p-lg-5 d-flex d-column">
            <div>
                <h1 class="mb-0">
                    @ViewData["FirstName"]
                    <span class="text-primary">@ViewData["LastName"] </span>
                </h1>
                <hr />
                <span class="h1">@ViewData["Page"]</span>
                @RenderBody()
            </div>
        </section>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MyCVHenrikPrangel/Views/Skills/Languages.cshtml
@model IEnumerable<Domain.Language>

@{
    ViewData["Title"] = "Languages";
}


<br />
<br />
<br />
<p> My language related abilities on a scale of 0-5</p>
<p> With proof of said ability</p>
<section class="resume-section">
    <section class="table">
        <table class="subheading mb-5" width="1000">
            <thead class="table-dark">
                <tr class="text-center">
                    <th>
                    </th>
                    <th>
                        Understanding
                    </th>
                    <th>
                        Speaking
                    </th>
                    <th>
                        Writing
                    </th>
                    <th>
                        
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="table">
                @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.LanguageName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Understanding)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Speaking)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Writing)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Comment)
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </section>
</section>

MyCVHenrikPrangel/Views/Skills/Skills.cshtml
@model IEnumerable<Domain.Skills>

@{
    ViewData["Title"] = "Skills";
}

<br />
<br />
<br />
<p> (The measurement system used is completely made up by me, and is based on my own assumptions on beginner level programming.)</p>
<p >
    <span class="text-dark">STUDY TIME </span> - for most part, this means how much emphasis and time has been put on the mentioned topic,
    in school, and how much time i myself have devoted to studying it
</p>
<p >
    <span class="text-dark">HOW I FEEL USING</span> - shows how i feel about my skills with the mentioned technology,
    considering I'm a beginner (Comfortable meaning i feel that my skill level is sufficient for where I'm at, insecure meaning
    that more studying and skill improvement needs to be done)
</p>

<section class="resume-section">
    <section class="table">
        <table class="subheading mb-5" width="1000">
            <thead class="table-dark">
                <tr class="text-center">
                    <th>
                    </th>
                    <th>
                        Study Time
                    </th>
                    <th>
                        How i feel using
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td>
                            @Html.DisplayFor(modelItem => item.SkillName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StudyTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Opinion)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </section>
</section>